name: Create Release

on:
  push:
    branches:
      - main
    paths:
    - '**.json'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Version Number
      id: version
      run: echo "::set-output name=version::$(cat package.json | jq -r .version)"
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
